builds:
  # List of builds
  - # First Build
    env:
    - CGO_ENABLED=0
    main: cmd/sensu-goalert-handler/main.go
    # Set the binary output location to bin/ so archive will comply with Sensu Go Asset structure
    binary: bin/{{ .ProjectName }}
    goos:
      - linux
    goarch:
      - amd64
    ignore:
      # TODO: add freebsd/arm support to gopsutil
      - goos: freebsd
        goarch: arm

checksum:
  # You can change the name of the checksums file.
  # Default is `{{ .ProjectName }}_{{ .Version }}_checksums.txt`.
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha256-checksums.txt"

archive:
  format: tar.gz
  files:
    - README.md
    - LICENSE.md

  # You can change the name of the GitHub release.
  # This is parsed with the Go template engine and the following variables
  # are available:
  # - ProjectName
  # - Tag
  # - Version (Git tag without `v` prefix)
  # Default is ``
  #name_template: "{{.ProjectName}}-v{{.Version}}"